name: Java CI with Maven

on:
  push:
    branches:
      - main  # 触发 CI 的分支，可以根据需要调整
  pull_request:
    branches:
      - main  # 触发 CI 的 PR 可以针对的分支

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'

      - name: Build with Maven
        run: mvn clean install

      - name: Run TestNG tests
        run: mvn test -DsuiteXmlFile=testng.xml